openapi: 3.0.1
info:
  title: Assessment Item API(s)
  description: "- The Assessment API resources are used for managing the questions\
    \ known as **Assessment items**.  \n- The Assessment API resources provides the\
    \ basic functionality to perform the operations like Creating, Reading,  Updating,\
    \ deleting these assessment items.  \n- The URL for Assessment Item API(s) is\
    \ `action/assessment/v3/items`"
  termsOfService: https://github.com/project-sunbird/sunbird-commons/blob/master/LICENSE
  contact:
    email: info@sunbird.org
  version: "1.0"
servers:
- url: https://staging.open-sunbird.org/action/assessment/v3/items
paths:
  /create:
    post:
      tags:
      - Assessment Item API(s)
      summary: Create Assessment Item
      description: "This API is used for creating an assessment Item.\n  - The endpoint\
        \ for **Create Assessment Item** is `/create`\n  - The fields marked with\
        \ an asterisk (*) are mandatory. They cannot be null or empty.\n  "
      operationId: CreatePost
      parameters:
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.Possible\
          \ media types can be:- \n  - Application/json\n  - Multipart/form-data\n\
          \  - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: User_ID
        in: header
        description: The Registered User ID to execute the API.
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: To make use of any User API, you require bearerorization. Raise
          a request to the administrator for the use of the API. You will receive
          the authorization key. Specify the key received, here.
        required: true
        schema:
          type: string
      requestBody:
        description: "'The body parameter refers to the format of the request, the\
          \ request body (payload) takes the following media types to make the payload:'\n\
          \   \n   - JSON \n   - XML data\n \n The body is the representation of the\
          \ resource object for creating a new assessment item."
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Questionsaverequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Questionsaverequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Questionsaverequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Create Assessment Item" operation
            was successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Create Assessment Item" operation failed
            ! The possible reason for failure is that you may have missed providing
            input for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! We
            track these errors automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
      security:
      - bearer: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /update/{AssessmentItem_ID}:
    patch:
      tags:
      - Assessment Item API(s)
      summary: Update an Assessment Item
      description: "This API is associated with updating an assessment Item.\n  -\
        \ The endpoint for **Update an Assessment Item** is `/update/{do_112875566089461760111}`\n\
        \  - The fields marked with an asterisk (*) are mandatory. They cannot be\
        \ null or empty.\n  \n  "
      operationId: UpdateEkNIbASsncBp14Patch
      parameters:
      - name: AssessmentItem_ID
        in: path
        description: Please append a valid Assessment ID to the Request URL
        required: true
        schema:
          type: string
      - name: user-id
        in: header
        description: The Registered User ID to execute the API.
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.Possible\
          \ media types can be:- \n  - Application/json\n  - Multipart/form-data\n\
          \  - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: To make use of any User API, you require authorization. Raise
          a request to the administrator for the use of the API. You will receive
          the authorization key. Specify the key received, here.
        required: true
        schema:
          type: string
      requestBody:
        description: "'The body parameter refers to the format of the request, the\
          \ request body (payload) takes the following media types to make the payload:'\n\
          \   \n   - JSON \n   - XML data\n \n The body is the representation of the\
          \ resource object for updating an assessment item."
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Questionupdaterequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Questionupdaterequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Questionupdaterequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Update Assessment Item" operation
            was successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Update Assessment Item" operation failed
            ! The possible reason for failure is that you may have missed providing
            input for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! We
            track these errors automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /update/ek.n.ib.a.ssnc.bp1.4
          headers:
            Content-Type: application/json
            user-id: ilimi
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "assessment_item": {
                  "identifier": "ek.n.ib.a.ssnc.bp1.4",
                  "objectType": "AssessmentItem",
                  "metadata": {
              "type": "mcq",
              "lastUpdatedBy": "csv-import",
              "used_for": "worksheet",
              "num_answers": 1,
              "max_score": 1,
              "partial_scoring": false,
              "code": "ek.n.ib.a.ssnc.bp1.4",
              "title": "acvv",
              "question": "7 + 0  = ?",
              "question_image": "q24body",
              "question_count": 15,
              "domain": "Numeracy",
              "language": [
                "Hindi"
              ],
              "gradeLevel": [
                "Grade 1"
              ],
              "qlevel": "EASY",
              "keywords": [
                "addition",
                "add",
                "sum"
              ],
              "media": [
                {
                  "id": "q24body",
                  "type": "image",
                  "asset_id": "do_20043488",
                  "src": "https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png"
                },
                {
                  "id": "q24body",
                  "type": "image",
                  "asset_id": "do_20043488",
                  "src": "https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png"
                }
              ],
              "options": [
                {
                  "value": {
                    "type": "mixed",
                    "text": "8",
                    "asset": "8",
                    "index": 0
                  },
                  "answer": false
                },
                {
                  "value": {
                    "type": "mixed",
                    "text": "7",
                    "image": "q2body",
                    "asset": "7",
                    "index": 1
                  },
                  "answer": true
                },
                {
                  "value": {
                    "type": "mixed",
                    "text": "1",
                    "asset": "1",
                    "index": 2
                  },
                  "answer": false
                },
                {
                  "value": {
                    "type": "mixed",
                    "text": "4",
                    "asset": "4",
                    "index": 3
                  },
                  "answer": false
                }
              ],
              "template": "org.ekstep.mcq.t.ta",
              "template_id": "domain_3490",
              "model": {
                "param1": "7",
                "param2": "1"
              },
              "rownum": 5,
              "portalOwner": "128",
              "name": "acvv",
              "identifier": "ek.n.ib.a.ssnc.bp1.4"
            }
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Question - Update
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /read/{AssessmentItem_ID}:
    get:
      tags:
      - Assessment Item API(s)
      summary: Get an Assessment Item
      description: "This API is associated with  fetching a specific assessment Item.\n\
        \  - The endpoint for **Get an Assessment Item** is `/read/{do_112875566089461760111}`\n\
        \  - The fields marked with an asterisk (*) are mandatory. They cannot be\
        \ null or empty.\n  "
      operationId: ReadWingsD01Get
      parameters:
      - name: AssessmentItem_ID
        in: path
        description: Please append a valid Assessment ID to the Request URL
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.Possible\
          \ media types can be:- \n  - Application/json\n  - Multipart/form-data\n\
          \  - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: user-id
        in: header
        description: The Registered User ID to execute the API.
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: To make use of any User API, you require authorization. Raise
          a request to the administrator for the use of the API. You will receive
          the authorization key. Specify the key received, here.
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK ! Successful operation."Read Assessment Item" operation
            was successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Read Assessment Item" operation failed !
            The possible reason for failure is that you may have missed providing
            input for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! We
            track these errors automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: GET
          uri: /read/wings.D.01
          headers:
            Content-Type: application/json
            user-id: rayuluv
            Authorization: Bearer {{api_key}}
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Question - Get
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /retire/{AssessmentItem_ID}:
    delete:
      tags:
      - Assessment Item API(s)
      summary: Delete an Assessment Item
      description: "This API is associated with deleting an assessment Item.\n  -\
        \ The endpoint for **Delete an Assessment Item** is `/retire/{do_112875566089461760111}`\n\
        \  - The fields marked with an asterisk (*) are mandatory. They cannot be\
        \ null or empty.\n  "
      operationId: RetireQ1SUrduDelete
      parameters:
      - name: AssessmentItem_ID
        in: path
        description: Please append a valid Assessment ID to the Request URL
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.Possible\
          \ media types can be:- \n  - Application/json\n  - Multipart/form-data\n\
          \  - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: User_ID
        in: header
        description: Represents the authorized User ID to execute the API.
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: To make use of any User API, you require authorization. Raise
          a request to the administrator for the use of the API. You will receive
          the authorization key. Specify the key received, here.
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK ! Successful operation."Delete Assessment Item" operation
            was successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Delete Assessment Item" operation failed
            ! The possible reason for failure is that you may have missed providing
            input for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! We
            track these errors automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /retire/{Assessment_Id}
          headers:
            Content-Type: application/json
            user-id: <>
            Authorization: Bearer {{api_key}}
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Question - Delete
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /search:
    post:
      tags:
      - Assessment Item API(s)
      summary: Search an Assessment Item
      description: "This API is associated with searching an assessment Item.\n  -\
        \ The endpoint for **Search an Assessment Item** is `/search`\n  - The fields\
        \ marked with an asterisk (*) are mandatory. They cannot be null or empty.\n\
        \  "
      operationId: SearchPost
      parameters:
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.Possible\
          \ media types can be:- \n  - Application/json\n  - Multipart/form-data\n\
          \  - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: User_ID
        in: header
        description: The Registered User ID to execute the API.
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: To make use of any User API, you require authorization. Raise
          a request to the administrator for the use of the API. You will receive
          the authorization key. Specify the key received, here.
        required: true
        schema:
          type: string
      requestBody:
        description: "'The body parameter refers to the format of the request, the\
          \ request body (payload) takes the following media types to make the payload:'\n\
          \   \n   - JSON \n   - XML data\n \n The body is the representation of the\
          \ resource object for\n searching an Assessment item"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Questionsearchrequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Questionsearchrequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Questionsearchrequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Search Assessment Item" operation
            was successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Search Assessment Item" operation failed
            ! The possible reason for failure is that you may have missed providing
            input for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! We
            track these errors automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /search
          headers:
            Content-Type: application/json
            user-id: <>
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "metadata": {
                    "filters": [
                        {"property" : "template_id", "operator": "=", "value": "domain_3490"}
                    ]
                },
                "sortOrder": [
                    {"sortField": "code", "sortOrder": "ASC"}
                ],
                "startPosition": 0,
                "resultSize": 10
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Question - Search
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
components:
  schemas:
    Questionsearchrequest:
      title: The request body for seaching a question in an assessment
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request'
      example:
        request:
          metadata:
            filters:
            - property: template_id
              operator: =
              value: domain_3490
          sortOrder:
          - sortField: code
            sortOrder: (ABC)
          startPosition: 0
          resultSize: 10
    Request:
      title: Request
      required:
      - metadata
      - resultSize
      - sortOrder
      - startPosition
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/Metadata'
        sortOrder:
          type: array
          description: Represents the sorting order
          example:
          - sortField: <code>
            sortOrder: <ASC>
          items:
            $ref: '#/components/schemas/SortOrder'
        startPosition:
          type: integer
          description: ""
          format: int32
        resultSize:
          type: integer
          description: ""
          format: int32
      example:
        metadata:
          filters:
          - property: template_id
            operator: =
            value: domain_3490
        sortOrder:
        - sortField: <code>
          sortOrder: (ASC)
        startPosition: <0>
        resultSize: <10>
    Metadata:
      title: Metadata
      required:
      - filters
      type: object
      properties:
        filters:
          type: array
          description: ""
          example:
          - property: template_id
            operator: =
            value: domain_3490
          items:
            $ref: '#/components/schemas/Filter'
      example:
        filters:
        - property: template_id
          operator: =
          value: domain_3490
    Filter:
      title: Filter
      required:
      - operator
      - property
      - value
      type: object
      properties:
        property:
          type: string
          description: ""
          example: template_id
        operator:
          type: string
          description: ""
          example: =
        value:
          type: string
          description: ""
          example: domain_3490
      example:
        property: template_id
        operator: =
        value: domain_3490
    SortOrder:
      title: Represents the sorting format/order
      required:
      - sortField
      - sortOrder
      type: object
      properties:
        sortField:
          type: string
          description: ""
          example: code
        sortOrder:
          type: string
          description: ""
          example: <ASC>
      example:
        sortField: <code>
        sortOrder: <ASC>
    Questionsaverequest:
      title: The request body for save question
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/questsave'
    questsave:
      title: Request6
      required:
      - assessment_item
      type: object
      properties:
        assessment_item:
          $ref: '#/components/schemas/AssessmentItem'
    AssessmentItem:
      title: AssessmentItem
      required:
      - identifier
      - metadata
      - objectType
      type: object
      properties:
        identifier:
          type: string
          description: The unique ID for a question
          example: test.mcq_mixsed_zaxabc
        objectType:
          type: string
          description: ""
          example: AssessmentItem
        metadata:
          $ref: '#/components/schemas/Metadata8'
    Metadata8:
      title: Metadata8
      required:
      - code
      - feedback
      - max_score
      - model
      - name
      - num_answers
      - options
      - outRelations
      - owner
      - partial_scoring
      - qlevel
      - question
      - responses
      - tags
      - template_id
      - title
      - type
      - versionKey
      type: object
      properties:
        code:
          type: string
          description: 'The unique code for identifying a question '
          example: test.mcq_misxed_115
        name:
          type: string
          description: ""
          example: Mmcq Question 2
        type:
          type: string
          description: ""
          example: mcq
        framework:
          type: string
          description: Represents the name of the framework
          example: NCF
        board:
          type: string
          description: Represents the name of entity, organization.t gets populated
            using a framework
          example: NCERT
        medium:
          type: string
          description: Represents the medium followed, medium relates to language
            used. It gets populated using a framework
          example: English
        subject:
          type: string
          description: Represents the name of the subject.t gets populated using a
            framework
          example: History
        gradeLevel:
          type: array
          description: Represents the value for grade\Level of the content.t gets
            populated using a framework
          example:
          - Class 1
          items:
            type: string
        topic:
          type: array
          description: Represents the value for topic in content.t gets populated
            using a framework
          example:
          - Topic 1
          items:
            type: string
        num_answers:
          type: integer
          description: ""
          format: int32
          example: 2
        template_id:
          type: string
          description: ""
          example: mcq_mmtemplate_2
        qlevel:
          type: string
          description: ""
          example: MEDIUM
        owner:
          type: string
          description: ""
          example: username_2
        versionKey:
          type: string
          description: ""
          example: "1478768137225"
        title:
          type: string
          description: ""
          example: ಈ ಚaಿತ್ರದ ವಿಸ್xsxxxxxxxxxxxxತೀರ್ಣವನ್ನುzsaZZ ಹಾಗೂ ಸುತ್ತಳತೆಯನ್ನು
            ಲೆಕ್ಕ ಮಾಡಿ.  ಸೂಕ್ತ ಉತ್ತರವನ್ನು ಆರಿಸಿರಿ.
        question:
          type: string
          description: A representation of questions
          example: "ವಿಸ್ತೀರ್ಣ = ___________ ಚದರ ಸೆಂ.ಮೀ.             \nಸುತ್ತಳತೆ= __________\
            \ ಚದರ ಸೆಂ.ಮೀ."
        model:
          $ref: '#/components/schemas/Model'
        options:
          type: array
          description: ""
          items:
            $ref: '#/components/schemas/Option'
        tags:
          type: array
          description: ""
          example:
          - english
          - hindi
          items:
            type: string
        max_score:
          type: integer
          description: ""
          format: int32
          example: 1
        partial_scoring:
          type: boolean
          description: ""
          example: false
        feedback:
          type: string
          description: ""
        responses:
          type: array
          description: ""
          example:
          - values:
              12&10: true
            score: 1
          items:
            $ref: '#/components/schemas/Response'
        outRelations:
          type: array
          description: ""
          example:
          - endNodeId: Num:C1:SC1
            relationType: associatedTo
          - endNodeId: Num:C1:SC1
            relationType: associatedTo
          items:
            $ref: '#/components/schemas/OutRelation'
    Model:
      title: Model
      required:
      - img
      - img2
      - subtext
      type: object
      properties:
        img:
          $ref: '#/components/schemas/Img'
        img2:
          $ref: '#/components/schemas/Img'
        subtext:
          type: string
          description: ""
          example: (          = 1  ಚದರ ಸೆಂ.ಮೀ)
      example:
        img:
          type: image
          asset: persximeter
        img2:
          type: image
          asset: smallssssssSquare
        subtext: (          = 1  ಚದರ ಸೆಂ.ಮೀ)
    Img:
      title: Img
      required:
      - asset
      - type
      type: object
      properties:
        type:
          type: string
          description: ""
          example: image
        asset:
          type: string
          description: ""
          example: persximeter
      example:
        type: image
        asset: persximeter
    Option:
      title: Option
      required:
      - value
      type: object
      properties:
        value:
          $ref: '#/components/schemas/Value'
        answer:
          type: boolean
          description: ""
          example: true
    Value:
      title: Value
      required:
      - asset
      - type
      type: object
      properties:
        type:
          type: string
          description: ""
          example: text
        asset:
          type: string
          description: ""
          example: 12&10
      example:
        type: text
        asset: 12&10
    Response:
      title: Response
      required:
      - score
      - values
      type: object
      properties:
        values:
          $ref: '#/components/schemas/Values'
        score:
          type: integer
          description: ""
          format: int32
          example: 1
      example:
        values:
          12&10: true
        score: 1
    Values:
      title: Values
      required:
      - 12&10
      type: object
      properties:
        12&10:
          type: boolean
          description: ""
          example: true
      example:
        12&10: true
    OutRelation:
      title: OutRelation
      required:
      - endNodeId
      - relationType
      type: object
      properties:
        endNodeId:
          type: string
          description: ""
          example: Num:C1:SC1
        relationType:
          type: string
          description: ""
          example: associatedTo
      example:
        endNodeId: Num:C1:SC1
        relationType: associatedTo
    Questionupdaterequest:
      title: Question - UpdateRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request18'
      example:
        request:
          assessment_item:
            identifier: <>
            objectType: AssessmentItem
            metadata:
              type: mcq
              lastUpdatedBy: <>
              used_for: <>
              num_answers: <>
              max_score: <>
              partial_scoring: false
              code: ek.n.ib.a.ssnc.bp1.4
              title: acvv
              question: 7 + 0  = ?
              question_image: q24body
              question_count: 15
              domain: Numeracy
              language:
              - Hindi
              framework: NCF
              board: NCERT
              medium: English
              subject: History
              gradeLevel:
              - Class 1
              topic:
              - Topic 1
              qlevel: EASY
              keywords:
              - addition
              - add
              - sum
              media:
              - id: q24body
                type: image
                asset_id: do_20043488
                src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
              - id: q24body
                type: image
                asset_id: do_20043488
                src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
              options:
              - value:
                  type: mixed
                  text: 8
                  asset: 8
                  index: 0
                answer: false
              - value:
                  type: mixed
                  text: 7
                  image: q2body
                  asset: 7
                  index: 1
                answer: true
              - value:
                  type: mixed
                  text: 1
                  asset: 1
                  index: 2
                answer: false
              - value:
                  type: mixed
                  text: 4
                  asset: 4
                  index: 3
                answer: false
              template: org.ekstep.mcq.t.ta
              template_id: domain_3490
              model:
                param1: 7
                param2: 1
              rownum: 5
              portalOwner: 128
              name: acvv
              identifier: ek.n.ib.a.ssnc.bp1.4
    Request18:
      title: Request18
      required:
      - assessment_item
      type: object
      properties:
        assessment_item:
          $ref: '#/components/schemas/AssessmentItem19'
      example:
        assessment_item:
          identifier: ek.n.ib.a.ssnc.bp1.4
          objectType: AssessmentItem
          metadata:
            type: mcq
            lastUpdatedBy: csv-import
            used_for: worksheet
            num_answers: 1
            max_score: 1
            partial_scoring: false
            code: ek.n.ib.a.ssnc.bp1.4
            title: acvv
            question: 7 + 0  = ?
            question_image: q24body
            question_count: 15
            domain: Numeracy
            language:
            - Hindi
            gradeLevel:
            - Grade 1
            qlevel: EASY
            keywords:
            - addition
            - add
            - sum
            media:
            - id: q24body
              type: image
              asset_id: do_20043488
              src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
            - id: q24body
              type: image
              asset_id: do_20043488
              src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
            options:
            - value:
                type: mixed
                text: 8
                asset: 8
                index: 0
              answer: false
            - value:
                type: mixed
                text: 7
                image: q2body
                asset: 7
                index: 1
              answer: true
            - value:
                type: mixed
                text: 1
                asset: 1
                index: 2
              answer: false
            - value:
                type: mixed
                text: 4
                asset: 4
                index: 3
              answer: false
            template: org.ekstep.mcq.t.ta
            template_id: domain_3490
            model:
              param1: 7
              param2: 1
            rownum: 5
            portalOwner: 128
            name: acvv
            identifier: ek.n.ib.a.ssnc.bp1.4
    AssessmentItem19:
      title: AssessmentItem19
      required:
      - identifier
      - metadata
      - objectType
      type: object
      properties:
        identifier:
          type: string
          description: ""
          example: ek.n.ib.a.ssnc.bp1.4
        objectType:
          type: string
          description: ""
          example: AssessmentItem
        metadata:
          $ref: '#/components/schemas/Metadata20'
      example:
        identifier: ek.n.ib.a.ssnc.bp1.4
        objectType: AssessmentItem
        metadata:
          type: mcq
          lastUpdatedBy: csv-import
          used_for: worksheet
          num_answers: 1
          max_score: 1
          partial_scoring: false
          code: ek.n.ib.a.ssnc.bp1.4
          title: acvv
          question: 7 + 0  = ?
          question_image: q24body
          question_count: 15
          domain: Numeracy
          language:
          - Hindi
          gradeLevel:
          - Grade 1
          qlevel: EASY
          keywords:
          - addition
          - add
          - sum
          media:
          - id: q24body
            type: image
            asset_id: do_20043488
            src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
          - id: q24body
            type: image
            asset_id: do_20043488
            src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
          options:
          - value:
              type: mixed
              text: 8
              asset: 8
              index: 0
            answer: false
          - value:
              type: mixed
              text: 7
              image: q2body
              asset: 7
              index: 1
            answer: true
          - value:
              type: mixed
              text: 1
              asset: 1
              index: 2
            answer: false
          - value:
              type: mixed
              text: 4
              asset: 4
              index: 3
            answer: false
          template: org.ekstep.mcq.t.ta
          template_id: domain_3490
          model:
            param1: 7
            param2: 1
          rownum: 5
          portalOwner: 128
          name: acvv
          identifier: ek.n.ib.a.ssnc.bp1.4
    Metadata20:
      title: Metadata20
      required:
      - code
      - domain
      - gradeLevel
      - identifier
      - keywords
      - language
      - lastUpdatedBy
      - max_score
      - media
      - model
      - name
      - num_answers
      - options
      - partial_scoring
      - portalOwner
      - qlevel
      - question
      - question_count
      - question_image
      - rownum
      - template
      - template_id
      - title
      - type
      - used_for
      type: object
      properties:
        type:
          type: string
          description: ""
          example: mcq
        lastUpdatedBy:
          type: string
          description: ""
          example: csv-import
        used_for:
          type: string
          description: ""
          example: worksheet
        num_answers:
          type: integer
          description: ""
          format: int32
          example: 1
        max_score:
          type: integer
          description: ""
          format: int32
          example: 1
        partial_scoring:
          type: boolean
          description: ""
          example: false
        code:
          type: string
          description: ""
          example: ek.n.ib.a.ssnc.bp1.4
        title:
          type: string
          description: ""
          example: acvv
        question:
          type: string
          description: ""
          example: 7 + 0  = ?
        question_image:
          type: string
          description: ""
          example: q24body
        question_count:
          type: integer
          description: ""
          format: int32
          example: 15
        domain:
          type: string
          description: ""
          example: Numeracy
        language:
          type: array
          description: ""
          example:
          - Hindi
          items:
            type: string
        gradeLevel:
          type: array
          description: ""
          example:
          - Grade 1
          items:
            type: string
        qlevel:
          type: string
          description: ""
          example: EASY
        keywords:
          type: array
          description: ""
          example:
          - addition
          - add
          - sum
          items:
            type: string
        media:
          type: array
          description: ""
          example:
          - id: q24body
            type: image
            asset_id: do_20043488
            src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
          - id: q24body
            type: image
            asset_id: do_20043488
            src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
          items:
            $ref: '#/components/schemas/Medium'
        options:
          type: array
          description: ""
          example:
          - value:
              type: mixed
              text: 8
              asset: 8
              index: 0
            answer: false
          - value:
              type: mixed
              text: 7
              image: q2body
              asset: 7
              index: 1
            answer: true
          - value:
              type: mixed
              text: 1
              asset: 1
              index: 2
            answer: false
          - value:
              type: mixed
              text: 4
              asset: 4
              index: 3
            answer: false
          items:
            $ref: '#/components/schemas/Option22'
        template:
          type: string
          description: ""
          example: org.ekstep.mcq.t.ta
        template_id:
          type: string
          description: ""
          example: domain_3490
        model:
          $ref: '#/components/schemas/Model24'
        rownum:
          type: integer
          description: ""
          format: int32
          example: 5
        portalOwner:
          type: string
          description: ""
          example: "128"
        name:
          type: string
          description: ""
          example: acvv
        identifier:
          type: string
          description: ""
          example: ek.n.ib.a.ssnc.bp1.4
      example:
        type: mcq
        lastUpdatedBy: csv-import
        used_for: worksheet
        num_answers: 1
        max_score: 1
        partial_scoring: false
        code: ek.n.ib.a.ssnc.bp1.4
        title: acvv
        question: 7 + 0  = ?
        question_image: q24body
        question_count: 15
        domain: Numeracy
        language:
        - Hindi
        gradeLevel:
        - Grade 1
        qlevel: EASY
        keywords:
        - addition
        - add
        - sum
        media:
        - id: q24body
          type: image
          asset_id: do_20043488
          src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
        - id: q24body
          type: image
          asset_id: do_20043488
          src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
        options:
        - value:
            type: mixed
            text: 8
            asset: 8
            index: 0
          answer: false
        - value:
            type: mixed
            text: 7
            image: q2body
            asset: 7
            index: 1
          answer: true
        - value:
            type: mixed
            text: 1
            asset: 1
            index: 2
          answer: false
        - value:
            type: mixed
            text: 4
            asset: 4
            index: 3
          answer: false
        template: org.ekstep.mcq.t.ta
        template_id: domain_3490
        model:
          param1: 7
          param2: 1
        rownum: 5
        portalOwner: 128
        name: acvv
        identifier: ek.n.ib.a.ssnc.bp1.4
    Medium:
      title: Medium
      required:
      - asset_id
      - id
      - src
      - type
      type: object
      properties:
        id:
          type: string
          description: ""
          example: q24body
        type:
          type: string
          description: ""
          example: image
        asset_id:
          type: string
          description: ""
          example: do_20043488
        src:
          type: string
          description: ""
          example: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
      example:
        id: q24body
        type: image
        asset_id: do_20043488
        src: https://ekstep-public.s3-ap-southeast-1.amazonaws.com/content/q24body_1468995752684.png
    Option22:
      title: Option22
      required:
      - answer
      - value
      type: object
      properties:
        value:
          $ref: '#/components/schemas/Value23'
        answer:
          type: boolean
          description: ""
          example: false
      example:
        value:
          type: mixed
          text: 8
          asset: 8
          index: 0
        answer: false
    Value23:
      title: Value23
      required:
      - asset
      - index
      - text
      - type
      type: object
      properties:
        type:
          type: string
          description: ""
          example: mixed
        text:
          type: string
          description: ""
          example: "8"
        asset:
          type: string
          description: ""
          example: "8"
        index:
          type: integer
          description: ""
          format: int32
          example: 0
      example:
        type: mixed
        text: 8
        asset: 8
        index: 0
    Model24:
      title: Model24
      required:
      - param1
      - param2
      type: object
      properties:
        param1:
          type: string
          description: ""
          example: "7"
        param2:
          type: string
          description: ""
          example: "1"
      example:
        param1: 7
        param2: 1
    ContentCreateResponse:
      description: Create Content Response
      allOf:
      - $ref: '#/components/schemas/ResultWithNodeId'
      - $ref: '#/components/schemas/ResponseHeader'
    ResultWithNodeId:
      title: Result Containing Node Id
      type: object
      properties:
        result:
          $ref: '#/components/schemas/NodeId'
    ResponseHeader:
      title: ResponseHeader
      type: object
      properties:
        id:
          type: string
          description: API Identifier
        ver:
          type: string
          description: API version information
        ts:
          type: string
          description: API execution timespan
        params:
          $ref: '#/components/schemas/ResponseParams'
        responseCode:
          type: object
          properties: {}
          description: 'API response code '
    NodeId:
      title: Node Id
      type: object
      properties:
        node_id:
          type: string
          description: Node Identifier
    ResponseParams:
      title: Response Parameter
      type: object
      properties:
        resmsgid:
          type: string
          description: Response Message Id
        msgid:
          type: string
          description: Message Id
        err:
          type: string
          description: Error Code
        status:
          type: string
          description: Response Status
        errmsg:
          type: string
          description: Error Message
    ContentCreateErrorResponse:
      title: Create Content Error Response
      allOf:
      - $ref: '#/components/schemas/EmptyResult'
      - $ref: '#/components/schemas/ResponseHeader'
    EmptyResult:
      title: Empty Result
      type: object
      properties:
        result:
          type: object
          properties: {}
          description: Empty Result
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
    userToken:
      type: apiKey
      name: x-authenticated-user-token
      in: header
