openapi: 3.0.1
info:
  title: D.I.A.L code API(s)
  description: |-
    The D.I.A.L Code (Digital Infrastructure for Augmented Learning) API resources are used for energising the textbooks.
     - D.I.A.L code allows textbook creators to tag various pages and topics in a flexible manner using the DIAL codes (in QR code format) and these codes can be linked with digital content, thus providing easy access for the end users and a seamless physical to digital transition.
     - The URL for D.I.A.L code API(s) is `dialcode/v1`
  version: "1.0"
servers:
- url: https://staging.open-sunbird.org/api/dialcode/v1
paths:
  /generate:
    post:
      tags:
      - DIAL APIs
      summary: Generate DIAL code
      description: |-
        This API is associated with generating DIAL code.
           - The endpoint for **Generate DIAL code** is `/generate`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: GeneratePost
      parameters:
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for Generating DIAL code.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateDialcoderequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/GenerateDialcoderequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GenerateDialcoderequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Generate DIAL code" operation was
            successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Generate DIAL code" operation failed ! The
            possible reason for failure is that you may have missed providing input
            for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /generate
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "dialcodes": {
                  "count": 1,
                  "publisher": "Sunbird"
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Generate dialcode
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /publisher/create:
    post:
      tags:
      - DIAL APIs
      summary: Create Publisher
      description: |-
        This API is associated with creating a publisher. A publisher owns the DIAL code.
           - The endpoint for **Create Publisher** is `/publisher/create`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: PublisherCreatePost
      parameters:
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for Creating Publisher.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePublisherrequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreatePublisherrequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreatePublisherrequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Create Publisher" operation was
            successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Create Publisher" operation failed ! The
            possible reason for failure is that you may have missed providing input
            for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /publisher/create
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "publisher": {
                  "identifier": "Sunbird",
                  "name": "Sunbird Portal"
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Create publisher
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /process/status/{processId}:
    get:
      tags:
      - DIAL APIs
      summary: Get Process Status
      description: |-
        This API is associated with fetching the process Id while generating DIAL codes or when DIAL codes are listed.
           - The endpoint for **Get Process Status** is `/process/status/{processId}`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: ProcessStatusGet
      parameters:
      - name: processId
        in: path
        description: The process id is unique Id which is returned while generation
          or listing of DIAL codes
        required: true
        schema:
          type: string
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK ! Successful operation."Get Process Status" operation was
            successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Get Process Status" operation failed ! The
            possible reason for failure is that you may have missed providing input
            for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: GET
          uri: /process/status
          headers:
            X-Channel-ID: sunbird
            Content-Type: application/json
            Authorization: Bearer {{api_key}}
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get Process Status
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /read:
    post:
      tags:
      - DIAL APIs
      summary: Get DIAL Code
      description: "This API is associated with fetching/reading the DIAL code \n\
        \   - The endpoint for **Get DIAL code** is `/read`\n   - The fields marked\
        \ with an asterisk (*) are mandatory. They cannot be null or empty."
      operationId: ReadPost
      parameters:
      - name: X-Channel-ID
        in: header
        description: It the Unique ID to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for fetching/reading DIAL code
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDialcoderequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/GetDialcoderequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GetDialcoderequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Get DIAL code" operation was successfully
            executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Get DIAL code" operation failed ! The possible
            reason for failure is that you may have missed providing input for a mandatory
            parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /read
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "dialcode": {
                  "identifier": "Q13PMP"
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get dialcode
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /publisher/read/{publisherId}:
    get:
      tags:
      - DIAL APIs
      summary: Get Publisher
      description: |-
        This API is associated with fetching a specific publisher owning a DIAL code.
           - The endpoint for **Get Publisher** is `/publisher/read/publisherId`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: PublisherReadSunbirdGet
      parameters:
      - name: publisherId
        in: path
        description: It identifies a publisher uniquely
        required: true
        schema:
          type: string
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK ! Successful operation."Get Publisher" operation was successfully
            executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Get Publisher" operation failed ! The possible
            reason for failure is that you may have missed providing input for a mandatory
            parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: GET
          uri: /publisher/read/Sunbird
          headers:
            X-Channel-ID: sunbird
            Content-Type: application/json
            Authorization: Bearer {{api_key}}
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get publisher
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /update/{dialcode}:
    patch:
      tags:
      - DIAL APIs
      summary: Update DIAL code
      description: |-
        This API is associated with updating the DIAL code.
           - The endpoint for **Update DIAL code** is `/update/{dialcode}`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: UpdateQ13PMPPatch
      parameters:
      - name: dialcode
        in: path
        description: The dialcode identifier which you want to update
        required: true
        schema:
          type: string
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for updating DIAL code.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDialcoderequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateDialcoderequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateDialcoderequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Update DIAL code" operation was
            successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Update DIAL code" operation failed ! The
            possible reason for failure is that you may have missed providing input
            for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /update/Q13PMP
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "dialcode": {
                  "publisher": "Sunbird",
                  "tags": ["test"]
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: update dialcode
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /publisher/update/{publisherId}:
    patch:
      tags:
      - DIAL APIs
      summary: Update Publisher
      description: |-
        This API is associated with updating specific DIAL code publisher.
           - The endpoint for **Update Publisher** is `/publisher/update/{publisherId}`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: PublisherUpdateSunbirdPatch
      parameters:
      - name: publisherId
        in: path
        description: The publisher identifier which require to be updated
        required: true
        schema:
          type: string
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for updating specific publisher.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePublisherrequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdatePublisherrequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdatePublisherrequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Update Publisher" operation was
            successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Update Publisher" operation failed ! The
            possible reason for failure is that you may have missed providing input
            for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /publisher/update/Sunbird
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "publisher": {
                  "name": "Anuj Kumar Gupta"
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Update publisher
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /publish:
    post:
      tags:
      - DIAL APIs
      summary: Publish DIAL code
      description: |-
        This API is associated with publishing the  DIAL code.
           - The endpoint for **Publish DIAL code** is `/publish`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: PublishQ13PMPPost
      parameters:
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for Publishing DIAL code.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishDialcoderequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PublishDialcoderequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PublishDialcoderequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Publish DIAL code" operation was
            successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Publish DIAL code" operation failed ! The
            possible reason for failure is that you may have missed providing input
            for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /publish/Q13PMP
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Publish dialcode
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /content/link:
    post:
      tags:
      - DIAL APIs
      summary: Link DIAL code
      description: "This API is associated with linking DIAL code to the content\n\
        \ - The endpoint for **Link DIAL code** is `/content/link`\n - The fields\
        \ marked with an asterisk (*) are mandatory. They cannot be null or empty.\n\
        \ "
      operationId: ContentLinkPost
      parameters:
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for Linking DIAL code.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkDialcoderequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LinkDialcoderequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LinkDialcoderequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."Link DIAL code" operation was successfully
            executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "Link DIAL code" operation failed ! The possible
            reason for failure is that you may have missed providing input for a mandatory
            parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /content/link
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "content": {
                  "identifier": [""],
                  "dialcode": [""]
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Link dialcode
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /search:
    post:
      tags:
      - DIAL APIs
      summary: Search DIAL code
      description: |-
        This API is associated with searching a DIAL code.
           - The endpoint for **Search DIAL code** is `/search`
           - The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: SearchPost
      parameters:
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for searching DIAL code
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchDialcoderequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SearchDialcoderequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SearchDialcoderequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."search DIAL code" operation was
            successfully executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "search DIAL code" operation failed ! The
            possible reason for failure is that you may have missed providing input
            for a mandatory parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /search
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "search": {
                  "status": "Draft"
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Search dialcode
        x-testDescription: ""
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
  /list:
    post:
      tags:
      - DIAL APIs
      summary: List DIAL code
      description: "This API is associated with listing the DIAL codes \n   - The\
        \ endpoint for **List DIAL code** is `/list`\n   - The fields marked with\
        \ an asterisk (*) are mandatory. They cannot be null or empty."
      operationId: ListPost
      parameters:
      - name: X-Channel-ID
        in: header
        description: It the Unique Id to identify the root organization to which the
          user belongs
        required: true
        schema:
          type: string
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json\n   - Multipart/form-data\n\
          \   - Application/x-www-form-urlencoded"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All User APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      requestBody:
        description: |-
          The body refers to the format of the request.
            - The body contains metadata about the request for updating user notes.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListDialcoderequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ListDialcoderequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ListDialcoderequest'
        required: true
      responses:
        200:
          description: OK ! Successful operation."List DIAL code" operation was successfully
            executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateResponse'
        400:
          description: BAD REQUEST. The "List DIAL code" operation failed ! The possible
            reason for failure is that you may have missed providing input for a mandatory
            parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
      security:
      - bearer: []
      x-unitTests:
      - request:
          method: POST
          uri: /list
          headers:
            Content-Type: application/json
            X-Channel-ID: sunbird
            Authorization: Bearer {{api_key}}
          body: |-
            {
              "request": {
                "search": {
                  "publisher": "Sunbird"
                }
              }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: list dialcode
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      x-codegen-request-body-name: Body
components:
  schemas:
    GenerateDialcoderequest:
      title: Generate dialcodeRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request'
      example:
        request:
          dialcodes:
            count: 1
            publisher: Sunbird
    Request:
      title: Request
      required:
      - dialcodes
      type: object
      properties:
        dialcodes:
          $ref: '#/components/schemas/Dialcodes'
      example:
        dialcodes:
          count: 1
          publisher: Sunbird
    Dialcodes:
      title: Dialcodes
      required:
      - count
      - publisher
      type: object
      properties:
        count:
          type: integer
          description: ""
          format: int32
          example: 1
        publisher:
          type: string
          description: Represents the entity who  who owns the DIAL code
          example: Sunbird
      example:
        count: 1
        publisher: Sunbird
    CreatePublisherrequest:
      title: Create publisherRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request4'
      example:
        request:
          publisher:
            identifier: Sunbird
            name: Sunbird Portal
    Request4:
      title: Request4
      required:
      - publisher
      type: object
      properties:
        publisher:
          $ref: '#/components/schemas/Publisher'
      example:
        publisher:
          identifier: Sunbird
          name: Sunbird Portal
    Publisher:
      title: Publisher
      required:
      - identifier
      - name
      type: object
      properties:
        identifier:
          type: string
          description: Alphanumeric DIAL code generated by platform
          example: Sunbird
        name:
          type: string
          description: ""
          example: Sunbird Portal
      example:
        identifier: Sunbird
        name: Sunbird Portal
    GetDialcoderequest:
      title: Get dialcodeRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request7'
      example:
        request:
          dialcode:
            identifier: Q13PMP
    Request7:
      title: Request7
      required:
      - dialcode
      type: object
      properties:
        dialcode:
          $ref: '#/components/schemas/Dialcode'
      example:
        dialcode:
          identifier: Q13PMP
    Dialcode:
      title: Dialcode
      required:
      - identifier
      type: object
      properties:
        identifier:
          type: string
          description: Alphanumeric DIAL code generated by platform
          example: Q13PMP
      example:
        identifier: Q13PMP
    UpdateDialcoderequest:
      title: update dialcodeRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request10'
      example:
        request:
          dialcode:
            publisher: Sunbird
            tags:
            - test
    Request10:
      title: Request10
      required:
      - dialcode
      type: object
      properties:
        dialcode:
          $ref: '#/components/schemas/Dialcode11'
      example:
        dialcode:
          publisher: Sunbird
          tags:
          - test
    Dialcode11:
      title: Dialcode11
      required:
      - publisher
      - tags
      type: object
      properties:
        publisher:
          type: string
          description: ' Represents the entity who owns the DIAL code.'
          example: Sunbird
        tags:
          type: array
          description: ""
          example:
          - test
          items:
            type: string
      example:
        publisher: Sunbird
        tags:
        - test
    UpdatePublisherrequest:
      title: Update publisherRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request13'
      example:
        request:
          publisher:
            name: Anuj Kumar Gupta
    Request13:
      title: Request13
      required:
      - publisher
      type: object
      properties:
        publisher:
          $ref: '#/components/schemas/Publisher14'
      example:
        publisher:
          name: Anuj Kumar Gupta
    Publisher14:
      title: Publisher14
      required:
      - name
      type: object
      properties:
        name:
          type: string
          description: Name of Publisher
          example: Anuj Kumar Gupta
      example:
        name: Anuj Kumar Gupta
    PublishDialcoderequest:
      title: Publish dialcodeRequest
      required:
      - request
      type: object
      properties:
        request:
          type: object
          properties: {}
          description: ""
          example: {}
      example:
        request: {}
    LinkDialcoderequest:
      title: Link dialcodeRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request17'
      example:
        request:
          content:
            identifier:
            - ABCDF
            dialcode:
            - do_10101010
    Request17:
      title: Request17
      required:
      - content
      type: object
      properties:
        content:
          $ref: '#/components/schemas/Content'
      example:
        content:
          description: Alphanumeric DIAL code generated by platform
    Content:
      title: Content
      required:
      - dialcode
      - identifier
      type: object
      properties:
        identifier:
          type: array
          description: Alphanumeric DIAL code generated by platform
          example:
          - ""
          items:
            type: string
        dialcode:
          type: array
          description: ""
          example:
          - ""
          items:
            type: string
      example:
        identifier:
          description: Alphanumeric DIAL code generated by platform
    SearchDialcoderequest:
      title: Search dialcodeRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request20'
      example:
        request:
          search:
            status: Draft
    Request20:
      title: Request20
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          status: Draft
    Search:
      title: Search
      required:
      - status
      type: object
      properties:
        status:
          type: string
          description: ""
          example: Draft
      example:
        status: Draft
    ListDialcoderequest:
      title: list dialcodeRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request23'
      example:
        request:
          search:
            publisher: Sunbird
    Request23:
      title: Request23
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search24'
      example:
        search:
          publisher: Sunbird
    Search24:
      title: Search24
      required:
      - publisher
      type: object
      properties:
        publisher:
          type: string
          description: Represents the entity who owns the DIAL code
          example: Sunbird
      example:
        publisher: Sunbird
    ResultWithNodeId:
      title: Result Containing Node ID
      type: object
      properties:
        result:
          $ref: '#/components/schemas/NodeId'
    ContentCreateResponse:
      description: Create Content Response
      allOf:
      - $ref: '#/components/schemas/ResultWithNodeId'
      - $ref: '#/components/schemas/ResponseHeader'
    ResponseHeader:
      title: ResponseHeader
      type: object
      properties:
        id:
          type: string
          description: API Identifier
        ver:
          type: string
          description: API version information
        ts:
          type: string
          description: API execution timespan
        params:
          $ref: '#/components/schemas/ResponseParams'
        responseCode:
          type: object
          properties: {}
          description: 'API response code '
    ResponseParams:
      title: Response Parameter
      type: object
      properties:
        resmsgid:
          type: string
          description: Represents the response Message ID
        msgid:
          type: string
          description: Represents the error Message ID
        err:
          type: string
          description: Represents the Error Code
        status:
          type: string
          description: Response Status
        errmsg:
          type: string
          description: Error Message
    EmptyResult:
      title: Empty Result
      type: object
      properties:
        result:
          type: object
          properties: {}
          description: Empty Result
    NodeId:
      title: Node Id
      type: object
      properties:
        node_id:
          type: string
          description: Node Identifier
    ContentCreateErrorResponse:
      title: Create Content Error Response
      allOf:
      - $ref: '#/components/schemas/EmptyResult'
      - $ref: '#/components/schemas/ResponseHeader'
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
    userToken:
      type: apiKey
      name: x-authenticated-user-token
      in: header
